### PR TITLE
CARCH=x86-64

### PR DESCRIPTION
**Pull request by paugier**

### CODE REVIEW

**Comment by paugier** [comment]
See https://github.com/conda-forge/fluidsim-feedstock/pull/6

**Comment by paugier** [comment]
@conda-forge-admin, please rerender

**Comment by ashwinvis** [comment]
@paugier Wrong repo to send PR to. Also it seems that "rerender" does not work with PRs from organizational repos, like fluiddyn/... .

**Comment by paugier** [comment]
Oh yes of course! I'll try again. Github is too complicated for me :-)

**Pull request closed without merging**
